### ISSUE TITLE
Problems with shells other than bash

### ISSUE THREAD

**Issue by tacitsci** [yaml/yamlscript#5] opened 2023-06-05 13:10 UTC
For YAMLScript-0.1.4,

	yamlscript example/99-bottles.ys
	
runs correctly under bash, but hangs under zsh.

**Comment by ingydotnet** [comment] 2023-06-05 21:09
How did you install `yamlscript`?

Can you send me the output of these commands:
```
perl -V
which yamlscript
which bash
$(which bash) --version
echo $OSTYPE
```
yamlscript is a bash program that execs a perl program.
So bash and perl are both needed.
But the shell you run it from should not matter at all.
I just tested with this:

```
$ zsh
$ export PATH=/usr/local/bash-3.2.48/bin:$PATH
$ cpanm YAMLScript
YAMLScript is up to date. (0.1.4)
$ yamlscript eg/99-bottles.ys 3
3 bottles of beer on the wall,
3 bottles of beer.
Take one down, pass it around.
2 bottles of beer on the wall.

2 bottles of beer on the wall,
2 bottles of beer.
Take one down, pass it around.
1 bottle of beer on the wall.

1 bottle of beer on the wall,
1 bottle of beer.
Take one down, pass it around.
No more bottles of beer on the wall.

$ 
```

**Comment by tacitsci** [comment] 2023-06-06 14:39
*> *How did you install yamlscript?

First I tried the usual 'perl Makefile.PL;make;make test;make install'
under zsh and encountered some problems (/bin/sh: -c: line 1: syntax error
near unexpected token `('
). Then I started up 'bash' and repeated the install procedure and
everything worked fine. Earlier I encountered similar issues when
installing 'Lingy'.

> Can you send me the output of these commands: ...

*$* perl -V
Summary of my perl5 (revision 5 version 36 subversion 0) configuration:

  Platform:
    osname=linux
    osvers=4.4.0-19041-microsoft
    archname=x86_64-linux-thread-multi
    uname='linux desktop-96vsofa 4.4.0-19041-microsoft #1237-microsoft sat
sep 11 14:32:00 pst 2021 x86_64 gnulinux '
    config_args='-des -Dusethreads -Dprefix=/home/ta/.local/aeld/usrlocal'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='6.3.0 20170516'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib
/lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at May 28 2022 15:39:41
  @INC:

/home/ta/.local/aeld/usrlocal/lib/perl5/site_perl/5.36.0/x86_64-linux-thread-multi
    /home/ta/.local/aeld/usrlocal/lib/perl5/site_perl/5.36.0
    /home/ta/.local/aeld/usrlocal/lib/perl5/5.36.0/x86_64-linux-thread-multi
    /home/ta/.local/aeld/usrlocal/lib/perl5/5.36.0
    /home/ta/.local/aeld/usrlocal/lib/perl5/site_perl/5.34.1
    /home/ta/.local/aeld/usrlocal/lib/perl5/site_perl
*$* which yamlscript
/home/ta/.local/aeld/usrlocal/bin/yamlscript
*$* which bash
/bin/bash
*$* $(which bash) --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by ingydotnet** [comment] 2023-06-06 21:26
How did you download the YAMLScript and/or Lingy distributions?
I assume you got them from CPAN.
Could you send me the commands you use to get these?

Typically people don't manually install perl modules much these days. They use a CPAN client like `cpanm` or `cpan`.
It's fine that you are doing it manually but I need to know how to reproduce the problem.
So all the commands you used under zsh would be appreciated.

**Comment by tacitsci** [comment] 2023-06-07 02:09
Thanks for your help. Please don't expend an inordinate amount of effort
just to accommodate my specific situation.

Ordinarily, I use cpan to install modules. I install manually when I run
into problems (typically, failing tests) or if I have hard-to-install
prerequisites.

For most systems I use, my login shell is zsh. Lately, I have been using
Debian (under WSL) and Cygwin. I encountered this specific install problem
on both Debian and Cygwin.

My procedure on both Debian and Cygwin is as follows:

   - Try to install Lingy using cpan (fails)
   - Try to install Lingy using perl Makefile.PL; make; make test; make
   install (fails at the make stage)
   - In that same Lingy-... directory, start bash, and then do make; make
   test; make install (succeeds)
   - Exit from bash
   - Try to install YAMLScript using cpan (fails)
   - Try to install YAMLScript using perl Makefile.PL; make; make test;
   make install (fails at the make stage)
   - In that same YAMLScript-... directory, start bash, and then do make;
   make test; make install (succeeds)

I don't have an urgent need to use YAMLScript in my work, I just tried it
out because it looked cool.

I have VMware Workstation, so I'll try to gather more detailed error info
on some throwaway systems.

**Comment by ingydotnet** [comment] 2023-06-08 15:20
I'm not sure what's going on. I'm still wondering how you download the Lingy-x.x.x.tar.gz file. It would be nice to see the output of commands of a reproduction of your failing situation.

I did just release new versions of Lingy and YAMLScript that fixed install problems I had on a Mac. They should install ok with `cpan` now. Can you test that for me?

I take install problems fairly seriously because I know there are a lot of combinations of install environments out there.
It's not a waste of my time to figure these things out.

**Comment by ingydotnet** [comment] 2023-06-08 15:32
I just tested with `cpan` on both and it worked. But make sure you get Lingy-0.1.11.tar.gz and YAMLScript-0.1.5.tar.gz versions.

**Comment by tacitsci** [comment] 2023-06-09 14:33
I don't have MacOS, so you might want to try the experiment of temporarily setting your default shell to zsh and  then seeing if you observe the errors. Many people prefer bash as their default shell, but some like zsh.

Here are lightly edited cpan outputs under  Debian and Cygwin for Lingy 0.1.11. Fails at the target 'pure_all':

Debian:

    "/home/ta/.local/aeld/usrlocal/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/_lingy.pl
    cp bin/lingy blib/script/lingy
    "/home/ta/.local/aeld/usrlocal/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/lingy
    /bin/sh: 1: Syntax error: "(" unexpected
    Makefile:1053: recipe for target 'pure_all' failed
    make: *** [pure_all] Error 2

Cygwin:

    "/home/vmwx/.local/aeld/usrlocal/bin/perl.exe" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/lingy
    /bin/sh: -c: line 1: syntax error near unexpected token `('
    /bin/sh: -c: line 1: `PATH=blib/script:/home/vmwx/.local/bin: ...  blib/script/lingy'
    make: *** [Makefile:1055: pure_all] Error 2

**Comment by tacitsci** [comment] 2023-06-11 14:56
On FreeBSD 13.2, Lingy 0.1.11, YAMLScript 0.1.5, and Test::More::YAMLScript 0.1.3 all install cleanly under zsh.

**Comment by ingydotnet** [comment] 2023-06-17 19:34
Sweet! Closing this for now :)

**Closed by ingydotnet** 2023-06-17 19:34 UTC
